Pmyip3/page to import publications using g scholar ms
Researchify/Researchify pull request #101
Opened 2021-05-20 11:01 UTC by pmyip3

# Description 
When the import publication button is clicked and after the profile link is entered(accept any values for now), the hardcoded publications in json file will be displayed, which is pretended to be imported by scholar api (to be implemented).
The user should be able to click on the ones they want to insert and then when they're done, they click a button that sends that data to the backend to do a mass insert into the db. 

# Type of change 
- [ ] Bug fix
- [X] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
We need the feature of importing publications as per the client request. 

# Solution description

# Tests 
All unit tests pass? N/A

Builds successfully? Yes 

Attach screenshot of the expected result (e.g. UI of the website/ postman api call result/ database changes)
Profile Link would accpet any random characters for now
![image](https://user-images.githubusercontent.com/17608976/118965695-49e21980-b9ac-11eb-8707-f9b7b37a2d48.png)
After loading, a list of publications would be populated from the json file, a checkbox attahed to each of those
![image](https://user-images.githubusercontent.com/17608976/118965912-857ce380-b9ac-11eb-8ea3-1d15c1213660.png)
After the import button is clicked, the selected publications will be sent to db and displaying on the page 
![image](https://user-images.githubusercontent.com/17608976/118966394-0936d000-b9ad-11eb-8541-603f958c2c20.png)

Error message will pop up when there is error from the scholar api call 
![image](https://user-images.githubusercontent.com/17608976/118966744-3c795f00-b9ad-11eb-8fad-e91710d316d0.png)
* to test this feature, uncomment line 117-120 and comment out line 113-116
![image](https://user-images.githubusercontent.com/17608976/118966831-55821000-b9ad-11eb-8d20-263dcf278763.png)

# Relevant document/ link (if any) 
N/A

# Risk
Low for this PR alone, will to be integared to the actual google scholar api.

2021-05-20 11:09 UTC, rsun0013 approved these changes

2021-05-21 01:51 UTC, vgoh1 commented on client/src/components/publications/importedPublication/ImportedPublication.js
> +const ImportedPublciation = ({pub, index, setChecked}) => {
Typo for publication here

2021-05-21 01:52 UTC, vgoh1 commented on client/src/reducers/importedPublicationsReducer.js
> +const importedPublciationReducer = (state=initialState, action) => {
Typo for publication here

2021-05-21 01:57 UTC, aksh0001 commented on api/src/controllers/publications.js
> +async function importPublications(req, res) {
nit: documentation required for this controller

2021-05-21 01:57 UTC, vgoh1 commented
Besides the spelling mistakes + the static analyzer issues, great work! Please fix those up and then I'll hit approve. Thanks for adding the function to do the mass insert in the backend as well.

2021-05-21 01:57 UTC, aksh0001 commented on api/src/controllers/publications.js
> +    var result = await Team.findById(_id);
nit: prefer `const` over `var`

2021-05-21 01:58 UTC, aksh0001 commented on api/src/controllers/publications.js
> +
this validation would be a good candidate for middleware as we used previously?

2021-05-21 02:05 UTC, aksh0001 commented on client/src/components/publications/Publications.js
> +import { Button, Modal, Dropdown, DropdownButton, Container, Col, Row, Spinner, Alert } from 'react-bootstrap';
nit: Static Analyzer warnings about unused imports.

2021-05-21 02:05 UTC, aksh0001 commented on client/src/components/publications/form/ImportFailPage.js
> +import { Alert, Row, Button } from "react-bootstrap";
File header that describes what the page does would be nice.

2021-05-21 02:06 UTC, aksh0001 commented on client/src/components/publications/form/ImportForm.js
> +        }
minor: we need a default case here (as per the Static Analyzer warnings)

2021-05-21 02:06 UTC, aksh0001 commented on client/src/components/publications/form/ImportSuccessPage.js
> +import { useSelector, useDispatch } from 'react-redux'
same as above: file headers to describe the component.

2021-05-21 02:07 UTC, aksh0001 commented on client/src/components/publications/form/ProfileLinkPage.js
> +import { Row, InputGroup, Button, Form, Spinner } from "react-bootstrap";
Static Analyzer warnings unused import

2021-05-21 02:07 UTC, aksh0001 commented on client/src/components/publications/importedPublication/ImportedPublication.js
> +const ImportedPublciation = ({pub, index, setChecked}) => {
+1

2021-05-21 02:07 UTC, aksh0001 commented on client/src/components/publications/importedPublication/ImportedPublication.js
> +import { InputGroup, Form, Card, Collapse } from 'react-bootstrap';
File headers needed

2021-05-21 02:08 UTC, aksh0001 commented on client/src/components/publications/publicationsLayout/LayoutByCategory.js
>  import Publication from '../publication/Publication'
File headers as above.

2021-05-21 02:12 UTC, aksh0001 requested changes
Great job on the import UI, it looks really nice!
I think we could do with a bit more documentation before merging though.

2021-05-22 02:06 UTC, aksh0001 approved these changes

2021-05-22 02:10 UTC, vgoh1 approved these changes

2021-05-22 02:19 UTC, merged