Add achievements api
Researchify/Researchify pull request #153
Opened 2021-08-12 07:00 UTC by ssha0054

# Description 
Added api requests to create a new achievement, get all achievements for a team, update an achievement and delete an achievement.

# Type of change 
- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
Api endpoints are needed for the awards and achievement page.

# Solution description
- Create a new achievement via a `POST` request on the endpoint `/achievements/`
- Get all achievements via a `GET` request on the endpoint `/achievements/team/:team_id` , where `:team_id` is the mongo object id for the team.
- Delete an achievement via a `DELETE` request on the endpoint `/achievements/:id` , where `:id` is the mongo object id for the achievement
- Update an achievement via a `PATCH` request on the endpoint `/achievements/:id`, where `:id` is the mongo object id for the achievement

# Tests 
Tested the api requests on Insomnia. 

All unit tests pass? Yes

Builds successfully? Yes

# Relevant document/ link (if any) 
N/A

# Risk
Identity the risk level (low, medium, high) and indicate which component(s) will be affected if bugs exist.
Low

2021-08-12 09:33 UTC, pmyip3 requested changes
Can you use async/ await instead of promises? 
As we've created a ticket on converting all the existing controllers from promises to async/ await based on the previous discussion https://github.com/Researchify/Researchify/pull/140#discussion_r681393574
Would be nice if the incoming tickets are coded in async/ await style.

2021-08-12 14:36 UTC, ssha0054 commented
> Can you use async/ await instead of promises?
> As we've created a ticket on converting all the existing controllers from promises to async/ await based on the previous discussion [#140 (comment)](https://github.com/Researchify/Researchify/pull/140#discussion_r681393574)
> Would be nice if the incoming tickets are coded in async/ await style.

Yeah no worries, will make the changes.

2021-08-13 09:13 UTC, rpra0006 approved these changes

2021-08-13 23:44 UTC, aksh0001 commented on api/src/controllers/achievements.js
> +        const foundAchievement = await Achievement.aggregate([
nit: make this name plural.

2021-08-13 23:46 UTC, aksh0001 approved these changes
please see nit comments, but otherwise LGTM

2021-08-14 05:54 UTC, pmyip3 approved these changes

2021-08-14 06:01 UTC, merged

2021-08-14 06:19 UTC, vgoh1 commented
@ssha0054 Remember to hit squash and merge so the commits don't clog up the main branch, and also remember to delete your branch next time! Thanks!