Fix twitter integration
Researchify/Researchify pull request #158
Opened 2021-08-13 01:27 UTC by vgoh1

# Description 
Twitter integration was broken because when I refactored it over the break I didn't test this specific endpoint. This is the fix. Also added validation for the input and a loading spinner since it's around 1s where nothing is happening as you're fetching the Twitter data.

# Type of change 
- [x] Bug fix
- [ ] New feature
- [x] Refactoring
- [ ] Documentation 

# Problem
See description.

# Solution description
Validation using formik and yup (thanks Mable)
You don't have to click to show the input box now since I thought it was unnecessary.
Added loading spinner

# Tests 
These cases should be handled in the input box for the twitter handle:
- one or more spaces 
- a valid twitter account
- a twitter account that doesn't exist
- more than 15 chars
- empty string
Feel free to test for more.

# Relevant document/ link (if any) 
N/A

# Risk
Identity the risk level (low, medium, high) and indicate which component(s) will be affected if bugs exist.
Low

2021-08-13 02:52 UTC, aksh0001 commented on client/src/actions/team.js
> +    console.log(data);
Prefer not to leave raw logs in main.

2021-08-13 04:31 UTC, pmyip3 approved these changes

2021-08-13 15:35 UTC, aksh0001 commented on client/src/actions/team.js
> +    });
Please remove if not being used.

2021-08-13 15:36 UTC, aksh0001 commented on client/src/components/twitter/TwitterLink.js
> +  const [loadingState, setLoadingState] = useState(false);
nit: prefer calling this just `isLoading`, or equivalent; i.e. remove the `state` suffix as its implied.

2021-08-13 15:37 UTC, aksh0001 commented on client/src/reducers/teamReducer.js
> +      return { ...state, twitterFetchLoading: true };
Same, remove if unused.

2021-08-13 15:37 UTC, aksh0001 requested changes
Could you also address the SA checks for this file?
`client/src/components/layouts/DashboardSidebarData.js`

2021-08-14 03:01 UTC, vgoh1 commented
@aksh0001 re that SA warning: it's weird because BsUpload is being used in the file....so not sure why it's not picking that up. I think it's being removed in Jie's PR anyway so it should go away when that gets merged in.

2021-08-14 18:17 UTC, aksh0001 commented on client/src/actions/team.js
> +    console.log('unlink twitter');
nit: remove log

2021-08-14 18:18 UTC, aksh0001 approved these changes

2021-08-16 00:55 UTC, rpra0006 approved these changes
Looks good

2021-08-16 02:50 UTC, merged