Background for Login/Registration
Researchify/Researchify pull request #221
Opened 2021-09-14 14:09 UTC by jfan0010

# Description 
Added background for login and registration page

# Type of change 
- [ ] Bug fix
- [x] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
No bg before

# Solution description
As above

# Tests 
All unit tests pass? Y

Builds successfully? Y

Attach screenshot of the expected result (e.g. UI of the website/ postman api call result/ database changes)

![image](https://user-images.githubusercontent.com/48777884/133420630-958480a6-a154-4c38-bcef-1be740125e19.png)
![image](https://user-images.githubusercontent.com/48777884/133420657-e51fcf4f-208a-4275-8cb4-897473d2c37b.png)

# Risk
Identity the risk level (low, medium, high) and indicate which component(s) will be affected if bugs exist.
Medium - Low. Might affect registration/login feature.

2021-09-14 14:19 UTC, jfan0010 commented on client/src/components/auth/authComponents/LoginForm.jsx
> +/**
This file is the same as previous `Login.js`, just that removed the `Don't have account yet? Sign up today!` link beside the button.

2021-09-15 00:22 UTC, vgoh1 commented
Wow I can't believe how much better register/login looks when we change the background! I just had a few thoughts aesthetically:

What do you think of making the boxes match the ones on the landing page like below?
![image](https://user-images.githubusercontent.com/40584352/133350364-7b4e032c-6a21-4473-8071-ff2847c59827.png)

And the login/register buttons as well to match:
![image](https://user-images.githubusercontent.com/40584352/133350708-7d1a456f-1dd9-4b07-b21d-cd10f23cf653.png)
Or to match the login/register in the top right. Cause the bootstrap blue is looking a bit out of place right now.

2021-09-15 00:37 UTC, melvinalex7 approved these changes
Wow. The Login Page and Register Page look really good now. The transition to the login and register page is much better now—just a few suggestions.

1. 
![image](https://user-images.githubusercontent.com/53939479/133351420-5069f010-d99b-43dc-b56b-331418897f2a.png)
Should we add the nav links on the home page to the login and register page as well? Once you go to log in/register, all other links can only be accessed after going back to the home page.

2. 
![image](https://user-images.githubusercontent.com/53939479/133351621-c79981cd-7f52-46ad-b8a8-2304a98c3d1f.png)
Also, the register overlay is currently above the footer, which doesn't look right.

2021-09-15 00:57 UTC, jfan0010 commented
> Wow. The Login Page and Register Page look really good now. The transition to the login and register page is much better now—just a few suggestions.
> 
> 
> ![image](https://user-images.githubusercontent.com/53939479/133351420-5069f010-d99b-43dc-b56b-331418897f2a.png)
> Should we add the nav links on the home page to the login and register page as well? Once you go to log in/register, all other links can only be accessed after going back to the home page.
> 
> 
> ![image](https://user-images.githubusercontent.com/53939479/133351621-c79981cd-7f52-46ad-b8a8-2304a98c3d1f.png)
> Also, the register overlay is currently above the footer, which doesn't look right.

1. Yep we can, but the reason is the `nav links` in `landing page header` doesn't really work right now. And if it works, it will actually bring you to a different section on the `landing page` (not to different pages), not quite sure if we still need them if they're all navigating to the `landing page`. But yes I can add them back once the nav links are working.
2. Ops, can you also provide your screen dimension so that I can recreate the same issue and fix it?

2021-09-15 00:59 UTC, jfan0010 commented
> Wow I can't believe how much better register/login looks when we change the background! I just had a few thoughts aesthetically:
> 
> What do you think of making the boxes match the ones on the landing page like below?
> ![image](https://user-images.githubusercontent.com/40584352/133350364-7b4e032c-6a21-4473-8071-ff2847c59827.png)
> 
> And the login/register buttons as well to match:
> ![image](https://user-images.githubusercontent.com/40584352/133350708-7d1a456f-1dd9-4b07-b21d-cd10f23cf653.png)
> Or to match the login/register in the top right. Cause the bootstrap blue is looking a bit out of place right now.

I'll change them, btw do you think we should use the "brown gold" colour for the fonts or black as it is now is alright?

2021-09-15 01:13 UTC, vgoh1 commented
@jfan0010 Black because brown gold looks a bit out of place for normal body text imo.

2021-09-15 07:05 UTC, rpra0006 commented
> > Wow. The Login Page and Register Page look really good now. The transition to the login and register page is much better now—just a few suggestions.
> > ![image](https://user-images.githubusercontent.com/53939479/133351420-5069f010-d99b-43dc-b56b-331418897f2a.png)
> > Should we add the nav links on the home page to the login and register page as well? Once you go to log in/register, all other links can only be accessed after going back to the home page.
> > ![image](https://user-images.githubusercontent.com/53939479/133351621-c79981cd-7f52-46ad-b8a8-2304a98c3d1f.png)
> > Also, the register overlay is currently above the footer, which doesn't look right.
> 
> 1. Yep we can, but the reason is the `nav links` in `landing page header` doesn't really work right now. And if it works, it will actually bring you to a different section on the `landing page` (not to different pages), not quite sure if we still need them if they're all navigating to the `landing page`. But yes I can add them back once the nav links are working.
> 2. Ops, can you also provide your screen dimension so that I can recreate the same issue and fix it?

I think the "Researchify" button actually brings you to the landing page url. I tested it out in Mable's #222 and refreshes the page when you click on it.

2021-09-15 07:11 UTC, rpra0006 requested changes
![image](https://user-images.githubusercontent.com/53892953/133387176-775d3854-2846-4584-b908-23cac1fa5a2f.png)
I'm using 100% page size and the register form is cutting the footer border and covering the copyright text.

2021-09-15 07:13 UTC, rpra0006 requested changes
![image](https://user-images.githubusercontent.com/53892953/133387521-62b290d1-b95f-4382-96ce-ead862384275.png)
Login page is also a bit large, maybe you can remove some of the border spacing at the top and bottom of login form? The spacing between the landing header to the login form can also be reduced as well.

2021-09-15 10:53 UTC, jfan0010 commented
Changed the colour of forms and buttons. Should have fixed the footer issue, let me know if it doesn't fix 😢

2021-09-15 14:22 UTC, melvinalex7 commented
> Changed the colour of forms and buttons. Should have fixed the footer issue, let me know if it doesn't fix 😢

Looks like it is fixed when the zoom is 100% but when it goes to 110% the issue still persists.

2021-09-15 14:34 UTC, jfan0010 commented
> 
> Looks like it is fixed when the zoom is 100% but when it goes to 110% the issue still persists.

That is weird cause 110% on registration page and 125% on login page still work fine for me. But I think I would fix zooming issue later in the next ticket cause I might need some time to adjust the CSS configuration.

2021-09-16 05:07 UTC, rpra0006 requested changes
![image](https://user-images.githubusercontent.com/53892953/133552801-86bcec19-dfa6-4d46-9c56-1587241d799e.png)
I still have the same issue with registration but login looks great (only happens in laptop resolution but not desktop). If it's hard to fix, we can ignore this part for later?

 Also can you change the color of text inside "login" button, maybe to a white? It's hard to see brown on gold.

2021-09-16 05:36 UTC, jfan0010 commented
> I still have the same issue with registration but login looks great (only happens in laptop resolution but not desktop). If it's hard to fix, we can ignore this part for later?
> 
> Also can you change the color of text inside "login" button, maybe to a white? It's hard to see brown on gold.

😢 It shouldn't be hard to fix, just that I couldn't recreate the issue 🤣 . But I'll try it again later.

For the `login` button, black font is for the consistency with the `discover more` button on landing page, Not sure if we still wanna change them to white?

2021-09-16 05:53 UTC, rpra0006 commented
> > I still have the same issue with registration but login looks great (only happens in laptop resolution but not desktop). If it's hard to fix, we can ignore this part for later?
> > Also can you change the color of text inside "login" button, maybe to a white? It's hard to see brown on gold.
> 
> 😢 It shouldn't be hard to fix, just that I couldn't recreate the issue 🤣 . But I'll try it again later.
> 
> For the `login` button, black font is for the consistency with the `discover more` button on landing page, Not sure if we still wanna change them to white?

Idk I just think it's hard to see black on the dark gold color. Maybe someone else has an input?

2021-09-16 06:40 UTC, ssha0054 commented
> > > I still have the same issue with registration but login looks great (only happens in laptop resolution but not desktop). If it's hard to fix, we can ignore this part for later?
> > > Also can you change the color of text inside "login" button, maybe to a white? It's hard to see brown on gold.
> > 
> > 
> > 😢 It shouldn't be hard to fix, just that I couldn't recreate the issue 🤣 . But I'll try it again later.
> > For the `login` button, black font is for the consistency with the `discover more` button on landing page, Not sure if we still wanna change them to white?
> 
> Idk I just think it's hard to see black on the dark gold color. Maybe someone else has an input?

Yeah I agree with this. Personally I'm not a huge fan of the gold button, I think if it was similar to the Register button in being blue and white it will look better and is more readable. Since the register and log in page doesn't have any text matching the gold button like the landing page does, I reckon it looks quite inconsistent in the register and log in page.

2021-09-16 11:20 UTC, jfan0010 commented
I actually agree with you, but I was actually trying to match the original style on the `landing page` (top right on `landing page`: blue for `register` and `gold` for login), but because white background with gold font doesn't look good as a button in the form, I changed all the `log in` button to the same as the `discover more` button on the `landing page`. What if I change the login button to the gold background and white fonf, would that works?

![image](https://user-images.githubusercontent.com/48777884/133603005-9aebacde-034f-4ebc-8431-7fe59bd0d0a8.png)

2021-09-17 15:02 UTC, cyr17 commented
> I actually agree with you, but I was actually trying to match the original style on the `landing page` (top right on `landing page`: blue for `register` and `gold` for login), but because white background with gold font doesn't look good as a button in the form, I changed all the `log in` button to the same as the `discover more` button on the `landing page`. What if I change the login button to the gold background and white fonf, would that works?
> 
> ![image](https://user-images.githubusercontent.com/48777884/133603005-9aebacde-034f-4ebc-8431-7fe59bd0d0a8.png)

hmm maybe have white text in the gold button in both the discover more and login buttons , and this would make it look like it uses an inverted pallet of the login button from the landing page

2021-09-17 15:04 UTC, cyr17 approved these changes
Looks dope btw!

2021-09-18 03:53 UTC, rpra0006 approved these changes
Don't want to block this PR too long, but functionality wise good

2021-09-18 06:08 UTC, jfan0010 commented
Have changed the gold buttons to white font, applied some CSS to fix the overlapping issue (should have work now I guess, if not will pass it to others who can recreate the issue.) Will merge in now and maybe improve the CSS in the coming ticket if have time.

2021-09-18 06:10 UTC, merged