Incorrect login password bug
Researchify/Researchify pull request #224
Opened 2021-09-16 07:52 UTC by pmyip3

# Description 
Login fields show a green checkmark despite the wrong password. Toast popup showing "incorrect email/password". Needs a fix in the login field validation.
Also modified the register form to make it consistent. 

# Type of change 
- [x] Bug fix
- [ ] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
See below
![image](https://user-images.githubusercontent.com/17608976/133570874-f85318b5-c973-4c09-a562-5629798f140e.png)
![image](https://user-images.githubusercontent.com/17608976/133571018-4effda5a-f91f-4988-9c63-c627e9e88456.png)

# Solution description
Remove the toast and have validation in the login field
Change the login form to use formik, which support above the feature 

# Tests 
All unit tests pass? N/A

Builds successfully? Yes

Attach screenshot of the expected result (e.g. UI of the website/ postman api call result/ database changes)
![image](https://user-images.githubusercontent.com/17608976/133572102-a2bc2c14-6486-45da-9b8e-9e4ce66adba0.png)
![image](https://user-images.githubusercontent.com/17608976/133572246-30546783-7c7a-4d39-9da8-180b8e5782db.png)

Provide steps in detail for reviewers to reproduce the expected result of the code changes.
Test with the register and login functionality 

# Relevant document/ link (if any) 
https://stackoverflow.com/questions/56809526/handling-errors-from-api-with-formik

# Risk
Low

2021-09-16 12:07 UTC, kdav108 requested changes
Nice clean code! 

Just one UI suggestion, the "incorrect email/password" message appears underneath the password field:

<img width="416" alt="Screen Shot 2021-09-16 at 9 35 43 pm" src="https://user-images.githubusercontent.com/63642262/133608990-deea494d-fb5e-4b44-84da-2fea89892909.png">

It's a bit odd to have it appear there if the issue is with the email (like in the image above). 

Unfortunately the api doesn't give us enough detail on whether the issue is with password or email, and hence I'm wondering if we can make this error appear either under the Login button or above the "Email address" title. What do you think?

2021-09-17 09:54 UTC, pmyip3 commented
> Nice clean code!
> 
> Just one UI suggestion, the "incorrect email/password" message appears underneath the password field:
> 
> <img alt="Screen Shot 2021-09-16 at 9 35 43 pm" width="416" src="https://user-images.githubusercontent.com/63642262/133608990-deea494d-fb5e-4b44-84da-2fea89892909.png">
> 
> It's a bit odd to have it appear there if the issue is with the email (like in the image above).
> 
> Unfortunately the api doesn't give us enough detail on whether the issue is with password or email, and hence I'm wondering if we can make this error appear either under the Login button or above the "Email address" title. What do you think?

I think it makes sense to put a red box above the email address, but not sure if it's consistent with the current error handling? As we have the pop-up error message, error message on specific fields already. Or maybe we can simply also turn the email input fields red?

2021-09-17 15:06 UTC, cyr17 commented
> > Nice clean code!
> > Just one UI suggestion, the "incorrect email/password" message appears underneath the password field:
> > <img alt="Screen Shot 2021-09-16 at 9 35 43 pm" width="416" src="https://user-images.githubusercontent.com/63642262/133608990-deea494d-fb5e-4b44-84da-2fea89892909.png">
> > It's a bit odd to have it appear there if the issue is with the email (like in the image above).
> > Unfortunately the api doesn't give us enough detail on whether the issue is with password or email, and hence I'm wondering if we can make this error appear either under the Login button or above the "Email address" title. What do you think?
> 
> I think it makes sense to put a red box above the email address, but not sure if it's consistent with the current error handling? As we have the pop-up error message, error message on specific fields already. Or maybe we can simply also turn the email input fields red?

yes have both of them as red

2021-09-18 10:33 UTC, ssha0054 commented on client/src/actions/auth.js
> +      setFieldError('password', 'Incorrect email/ password');
Can remove the space before password in `email/ password`

2021-09-18 14:25 UTC, jfan0010 approved these changes
Tested. LGTM

2021-09-19 02:17 UTC, vgoh1 commented on client/src/components/auth/authComponents/LoginForm.jsx
> +      .required('Please Enter your Email'),
Can we have only have the first word with the first uppercase? Eg. 'Please enter your email'

2021-09-19 02:18 UTC, vgoh1 commented on client/src/components/auth/authComponents/LoginForm.jsx
> +      .required('Please Enter your password'),
'Please enter your password'

2021-09-19 02:19 UTC, vgoh1 commented on client/src/components/auth/authComponents/LoginForm.jsx
> +      .required('Please Enter your password'),
And to add, if possible, name here should be lowercase in the error message:
![image](https://user-images.githubusercontent.com/40584352/133913278-e9e82acf-256d-4255-8a1d-cd002d4093a4.png)

2021-09-19 06:06 UTC, rpra0006 approved these changes
Functionality works for me

2021-09-20 00:32 UTC, aksh0001 approved these changes

2021-09-21 09:43 UTC, merged