Publication layout options on scholly
Researchify/Researchify pull request #256
Opened 2021-10-02 07:32 UTC by pmyip3

# Description 
Displaying publications on scholly according to the sort by and group by options selected in Researchify 

# Type of change 
- [ ] Bug fix
- [x] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
The group by and sort by options for displaying publications is not implemented yet in scholly

# Solution description
Sorting function and group by components are added in scholly. 
Before rendering team publications on scholly, check the sort by and group by options and call the corresponding grouping and sorting functions

*** I copy the same groupbyCategory component (by using tabs) from layout 2 to layout 1 and 3, feel free to change it to have a different style. 

# Tests 
All unit tests pass? N/A

Builds successfully? Yes

Attach screenshot of the expected result (e.g. UI of the website/ postman api call result/ database changes)

Group by Category in layout 2
![image](https://user-images.githubusercontent.com/17608976/135707572-8bf1fed7-3619-4026-a756-97cefc32723d.png)

Provide steps in detail for reviewers to reproduce the expected result of the code changes.
Change the sorting and group by options on the publication page and deploy it. Check the deployed page and confirm if the publications follow the sorting/ group by options or not. 

# Relevant document/ link (if any) 
Any related documents could help reviewers to review this PR 

# Risk
Low

2021-10-03 04:44 UTC, kdav108 requested changes
Great work! I love the use of tabs for sorting by category.

I have noticed just one issue: with layout 1 when I sort by Category, the publications are no longer clickable, so I can't expand and see the description. As soon as I change back to grouping by `None`, it works fine.

This is without grouping by category, and I can click the publications:

<img width="1260" alt="Screen Shot 2021-10-03 at 3 43 29 pm" src="https://user-images.githubusercontent.com/63642262/135740287-6d29052e-8159-479e-9961-6ec583c28029.png">

With grouping by category, I can't click them:

<img width="1243" alt="Screen Shot 2021-10-03 at 3 36 30 pm" src="https://user-images.githubusercontent.com/63642262/135740301-6e6572e5-3c44-4f62-bd33-d86f3b8765a7.png">

2021-10-04 13:54 UTC, pmyip3 commented
> clickable

Thanks for catching this. 

> Great work! I love the use of tabs for sorting by category.
> 
> I have noticed just one issue: with layout 1 when I sort by Category, the publications are no longer clickable, so I can't expand and see the description. As soon as I change back to grouping by `None`, it works fine.
> 
> This is without grouping by category, and I can click the publications:
> 
> <img alt="Screen Shot 2021-10-03 at 3 43 29 pm" width="1260" src="https://user-images.githubusercontent.com/63642262/135740287-6d29052e-8159-479e-9961-6ec583c28029.png">
> 
> With grouping by category, I can't click them:
> 
> <img alt="Screen Shot 2021-10-03 at 3 36 30 pm" width="1243" src="https://user-images.githubusercontent.com/63642262/135740301-6e6572e5-3c44-4f62-bd33-d86f3b8765a7.png">

Thanks for catching the bug! Should be all fixed now.

2021-10-05 08:32 UTC, jfan0010 approved these changes
lgtm

2021-10-09 06:30 UTC, vgoh1 approved these changes

2021-10-09 11:20 UTC, merged